services:
  happyshop-mysql:
    image: mysql:8.0.46
    container_name: happyshop-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: happyshop_root_password
      MYSQL_DATABASE: happyshop
      MYSQL_USER: happyshop_user
      MYSQL_PASSWORD: happyshop_password
      TZ: Asia/Taipei
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - happyshop_mysql_data:/var/lib/mysql
      - ./database/schema/schema-v1.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  happyshop_mysql_data:
